//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeCryptoWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeCryptoWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string Button_AccountInformation_ChangePassword {
            get {
                return ResourceManager.GetString("Button_AccountInformation_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirme.
        /// </summary>
        public static string Button_CodeWindow_Join {
            get {
                return ResourceManager.GetString("Button_CodeWindow_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Button_ConfirmationButtons_Cancel {
            get {
                return ResourceManager.GetString("Button_ConfirmationButtons_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Button_ConfirmationButtons_Save {
            get {
                return ResourceManager.GetString("Button_ConfirmationButtons_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar pistas.
        /// </summary>
        public static string Button_ConfirmationButtons_SaveClues {
            get {
                return ResourceManager.GetString("Button_ConfirmationButtons_SaveClues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string Button_ConfirmationButtons_Send {
            get {
                return ResourceManager.GetString("Button_ConfirmationButtons_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar amigos.
        /// </summary>
        public static string Button_Friends_AddFriend {
            get {
                return ResourceManager.GetString("Button_Friends_AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar.
        /// </summary>
        public static string Button_friends_Invite {
            get {
                return ResourceManager.GetString("Button_friends_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Juego.
        /// </summary>
        public static string Button_GameRoom_StartGame {
            get {
                return ResourceManager.GetString("Button_GameRoom_StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Azul.
        /// </summary>
        public static string Button_GameRoom_TeamBlue {
            get {
                return ResourceManager.GetString("Button_GameRoom_TeamBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rojo.
        /// </summary>
        public static string Button_GameRoom_TeamRed {
            get {
                return ResourceManager.GetString("Button_GameRoom_TeamRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dar Pistas.
        /// </summary>
        public static string Button_InGame_GiveClue {
            get {
                return ResourceManager.GetString("Button_InGame_GiveClue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar juego.
        /// </summary>
        public static string Button_MenuGame_FindGame {
            get {
                return ResourceManager.GetString("Button_MenuGame_FindGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo juego.
        /// </summary>
        public static string Button_MenuGame_NewGame {
            get {
                return ResourceManager.GetString("Button_MenuGame_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        public static string Button_SignIn_Enter {
            get {
                return ResourceManager.GetString("Button_SignIn_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar como invitado.
        /// </summary>
        public static string Button_SignIn_EnterAsGuess {
            get {
                return ResourceManager.GetString("Button_SignIn_EnterAsGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú.
        /// </summary>
        public static string ComboBox_ManageMenu_Menu {
            get {
                return ResourceManager.GetString("ComboBox_ManageMenu_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string ComboBoxItem_GameRoom_Configuration {
            get {
                return ResourceManager.GetString("ComboBoxItem_GameRoom_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar Amigo.
        /// </summary>
        public static string ComboBoxItem_GameRoom_InviteFriend {
            get {
                return ResourceManager.GetString("ComboBoxItem_GameRoom_InviteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Perfil.
        /// </summary>
        public static string ComboBoxItem_GameRoom_ViewProfile {
            get {
                return ResourceManager.GetString("ComboBoxItem_GameRoom_ViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar empate.
        /// </summary>
        public static string ComboBoxItem_GameSettings_AcceptTie {
            get {
                return ResourceManager.GetString("ComboBoxItem_GameSettings_AcceptTie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida extra.
        /// </summary>
        public static string ComboBoxItem_GameSettings_ExtraRound {
            get {
                return ResourceManager.GetString("ComboBoxItem_GameSettings_ExtraRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string ComboBoxItem_MainWindow_English {
            get {
                return ResourceManager.GetString("ComboBoxItem_MainWindow_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string ComboBoxItem_MainWindow_Spanish {
            get {
                return ResourceManager.GetString("ComboBoxItem_MainWindow_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta.
        /// </summary>
        public static string ComboBoxItem_ManageMenu_Account {
            get {
                return ResourceManager.GetString("ComboBoxItem_ManageMenu_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de amigos.
        /// </summary>
        public static string ComboBoxItem_ManageMenu_FriendList {
            get {
                return ResourceManager.GetString("ComboBoxItem_ManageMenu_FriendList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informacion de cuenta.
        /// </summary>
        public static string Label_AccountInformation_AccountInformation {
            get {
                return ResourceManager.GetString("Label_AccountInformation_AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string Label_AccountInformation_Email {
            get {
                return ResourceManager.GetString("Label_AccountInformation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Label_AccountInformation_Password {
            get {
                return ResourceManager.GetString("Label_AccountInformation_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre usuario.
        /// </summary>
        public static string Label_AccountInformation_User {
            get {
                return ResourceManager.GetString("Label_AccountInformation_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa un código.
        /// </summary>
        public static string Label_CodeWindow_EnterCode {
            get {
                return ResourceManager.GetString("Label_CodeWindow_EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro que deseas reportar a.
        /// </summary>
        public static string Label_Confirmation_ReportPlayerConfirmation {
            get {
                return ResourceManager.GetString("Label_Confirmation_ReportPlayerConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado el juego.
        /// </summary>
        public static string Label_Error_GameNotFound {
            get {
                return ResourceManager.GetString("Label_Error_GameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloqueados.
        /// </summary>
        public static string Label_Friends_BlockedFriends {
            get {
                return ResourceManager.GetString("Label_Friends_BlockedFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Nickname.
        /// </summary>
        public static string Label_Friends_EnterNickname {
            get {
                return ResourceManager.GetString("Label_Friends_EnterNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos.
        /// </summary>
        public static string Label_Friends_Friends {
            get {
                return ResourceManager.GetString("Label_Friends_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado el nickname ingresado.
        /// </summary>
        public static string Label_Friends_NicknameNotFound {
            get {
                return ResourceManager.GetString("Label_Friends_NicknameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes.
        /// </summary>
        public static string Label_Friends_Request {
            get {
                return ResourceManager.GetString("Label_Friends_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código:.
        /// </summary>
        public static string Label_GameRoom_Code {
            get {
                return ResourceManager.GetString("Label_GameRoom_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugadores.
        /// </summary>
        public static string Label_GameRoom_Players {
            get {
                return ResourceManager.GetString("Label_GameRoom_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un equipo.
        /// </summary>
        public static string Label_GameRoom_SelectTeam {
            get {
                return ResourceManager.GetString("Label_GameRoom_SelectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En caso de empate.
        /// </summary>
        public static string Label_GameSettings_InCaseTie {
            get {
                return ResourceManager.GetString("Label_GameSettings_InCaseTie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de rondas.
        /// </summary>
        public static string Label_GameSettings_Rounds {
            get {
                return ResourceManager.GetString("Label_GameSettings_Rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuracion de partida.
        /// </summary>
        public static string Label_GameSettings_StartingConfiguration {
            get {
                return ResourceManager.GetString("Label_GameSettings_StartingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipo Azul.
        /// </summary>
        public static string Label_InGame_BlueTeam {
            get {
                return ResourceManager.GetString("Label_InGame_BlueTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comunicaciones.
        /// </summary>
        public static string Label_InGame_Comunications {
            get {
                return ResourceManager.GetString("Label_InGame_Comunications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dar una pista para.
        /// </summary>
        public static string Label_InGame_GiveClueFor {
            get {
                return ResourceManager.GetString("Label_InGame_GiveClueFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intercepciones.
        /// </summary>
        public static string Label_InGame_Interceptions {
            get {
                return ResourceManager.GetString("Label_InGame_Interceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipo Rojo.
        /// </summary>
        public static string Label_InGame_RedTeam {
            get {
                return ResourceManager.GetString("Label_InGame_RedTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ronda.
        /// </summary>
        public static string Label_InGame_RoundNumber {
            get {
                return ResourceManager.GetString("Label_InGame_RoundNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar el numero de palabra que coincide con.
        /// </summary>
        public static string Label_InGame_selectWordNumber {
            get {
                return ResourceManager.GetString("Label_InGame_selectWordNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico o usuario.
        /// </summary>
        public static string Label_MainWindow_EmailUser {
            get {
                return ResourceManager.GetString("Label_MainWindow_EmailUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Hola de nuevo!.
        /// </summary>
        public static string Label_MainWindow_Greeting {
            get {
                return ResourceManager.GetString("Label_MainWindow_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Ya tienes una cuenta?.
        /// </summary>
        public static string Label_Register_AlreadyAccount {
            get {
                return ResourceManager.GetString("Label_Register_AlreadyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento.
        /// </summary>
        public static string Label_Register_Birthday {
            get {
                return ResourceManager.GetString("Label_Register_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirma contraseña.
        /// </summary>
        public static string Label_Register_ConfirmPassword {
            get {
                return ResourceManager.GetString("Label_Register_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crea una cuenta.
        /// </summary>
        public static string Label_Register_CreateAccount {
            get {
                return ResourceManager.GetString("Label_Register_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Label_Register_Name {
            get {
                return ResourceManager.GetString("Label_Register_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportar Jugador.
        /// </summary>
        public static string Label_ReportPlayer_ReportPlayer {
            get {
                return ResourceManager.GetString("Label_ReportPlayer_ReportPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona el jugador.
        /// </summary>
        public static string Label_ReportPlayer_SelectPlayer {
            get {
                return ResourceManager.GetString("Label_ReportPlayer_SelectPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string Label_SignIn_ForgotPassword {
            get {
                return ResourceManager.GetString("Label_SignIn_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Necesitas una cuenta?.
        /// </summary>
        public static string Label_SignIn_NeedAccount {
            get {
                return ResourceManager.GetString("Label_SignIn_NeedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regístrate.
        /// </summary>
        public static string Label_SignIn_Register {
            get {
                return ResourceManager.GetString("Label_SignIn_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigo agregado.
        /// </summary>
        public static string Label_Success_FriendAdded {
            get {
                return ResourceManager.GetString("Label_Success_FriendAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña guardada con éxito.
        /// </summary>
        public static string Label_Success_PasswordSaved {
            get {
                return ResourceManager.GetString("Label_Success_PasswordSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración de partida guardada con éxito.
        /// </summary>
        public static string Label_Success_StartingConfigurationSaved {
            get {
                return ResourceManager.GetString("Label_Success_StartingConfigurationSaved", resourceCulture);
            }
        }
    }
}
